### PR TITLE
Add GPG signing keys to use when certifying releases

### PR DESCRIPTION
**Pull request by dalg24**
The intent is being able to have `PGP sig by [067309A139D9E57C](https://kokkos.org/signing-keys/dalg24.asc)` in the release notes

### CODE REVIEW

**Comment by lucbv** [comment]
@dalg24 adding my key in the same file and renaming it, would you rather have multiple files? I think this is more convenient to get them all at once instead of clicking multiple times.

**Comment by dalg24** [comment]
> @dalg24 adding my key in the same file and renaming it, would you rather have multiple files? I think this is more convenient to get them all at once instead of clicking multiple times.

I would rather have multiple files

**Comment by lucbv** [comment]
Alright adding each keys separately

**Comment by dalg24** [comment]
WTH why did you rename the keys and add that `-keys` suffix? :@

**Comment by lucbv** [comment]
If you end up loosing one which has happened before it might be nice to be able to just add to this file instead of having: dalg24.asc and dalg24_2.asc...

**Comment by dalg24** [comment]
It's just a filename isn't it. The suffix has no effect. (I am not even sure if the extension really matters.) You can still append keys in the future as needed.

**Pull request merged**
